### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by zerotrust-community** [45Drives/cockpit-benchmark#4]
Hi, i unable to install, i get following error:

```
root@proxmox1:~/cockpit-benchmark# make install
Building benchmark
npm --prefix benchmark install
npm WARN deprecated @types/xlsx@0.0.36: This is a stub types definition for xlsx (https://github.com/sheetjs/js-xlsx). xlsx provides its own type definitions, so you don't need @types/xlsx installed!
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/download/@45Drives/cockpit-vue-components/0.1.0-beta2/a216666b3e9eb97a30cf47c0b947b4e5661798db - authentication token not provided

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-10-24T18_01_52_114Z-debug-0.log
make: *** [Makefile:80: benchmark/dist/index.html] Error 1
```
`npm -v 9.2.0`

**Comment by zerotrust-community** [comment]
after installing yarn and nodejs, i get this error:

```
root@proxmox1:~/cockpit-benchmark# make install
Building benchmark
yarn --cwd benchmark install
yarn install v1.22.19
info No lockfile found.
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@45drives%2fcockpit-css: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/root/cockpit-benchmark/benchmark/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
make: *** [Makefile:80: benchmark/dist/index.html] Error 1
```

**Comment by zerotrust-community** [comment]
error log file:  `/root/cockpit-benchmark/benchmark/yarn-error.log`

```
root@proxmox1:~/cockpit-benchmark# cat /root/cockpit-benchmark/benchmark/yarn-error.log
Arguments: 
  /usr/bin/node /usr/share/yarn/bin/yarn.js --cwd benchmark install

PATH: 
  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Yarn version: 
  1.22.19

Node version: 
  18.13.0

Platform: 
  linux x64

Trace: 
  Error: https://registry.yarnpkg.com/@45drives%2fcockpit-css: Not found
      at params.callback [as _callback] (/usr/share/yarn/lib/cli.js:66145:18)
      at self.callback (/usr/share/yarn/lib/cli.js:140890:22)
      at Request.emit (node:events:513:28)
      at Request.<anonymous> (/usr/share/yarn/lib/cli.js:141862:10)
      at Request.emit (node:events:513:28)
      at IncomingMessage.<anonymous> (/usr/share/yarn/lib/cli.js:141784:12)
      at Object.onceWrapper (node:events:627:28)
      at IncomingMessage.emit (node:events:525:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

npm manifest: 
  {
    "name": "benchmark",
    "private": true,
    "version": "0.0.0",
    "type": "module",
    "scripts": {
      "dev": "vite",
      "build": "vite build",
      "preview": "vite preview"
    },
    "dependencies": {
      "@45drives/cockpit-css": "^0.1.12",
      "@45drives/cockpit-helpers": "^0.1.19",
      "@tailwindcss/forms": "^0.5.2",
      "chart.js": "^3.9.1",
      "vue": "^3.2.37",
      "xlsx": "^0.18.5"
    },
    "devDependencies": {
      "@45drives/cockpit-vue-components": "^0.1.0-beta2",
      "@types/xlsx": "^0.0.36",
      "@vitejs/plugin-vue": "^3.0.0",
      "autoprefixer": "^10.4.8",
      "postcss": "^8.4.16",
      "tailwindcss": "^3.1.8",
      "vite": "^3.0.0",
      "vite-plugin-vue-type-imports": "^0.2.0"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile
root@proxmox1:~/cockpit-benchmark# 
```

**Comment by CholoTook** [comment]
I'd simply like to know where the install instructions are...

**Comment by awesomebil** [comment]
> I'd simply like to know where the install instructions are...

There aren't any exactly, you can clone the repo and build from source using the makefile which has an install command but it's broken right now as evidenced by this issue and the fact that the last commit was 2 years ago. I just decided to use the command line linux utilities to benchmark disk performance but you could look into fixing why it's broken if you want to install it my best guess is that it's a dependency issue.
